version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: rehearsal
      POSTGRES_USER: rehearsal_user
      POSTGRES_PASSWORD: pass1234
    ports:
      - "5432:5432"
